#!/bin/bash

TARGET="i686-w64-mingw32"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE=${WORKSPACE:-$SCRIPT_DIR}
BUILD_DIR="$WORKSPACE/build/build/$TARGET"
DIST_DIR="$WORKSPACE/build/dist/$TARGET"
RELEASE_DIR="$WORKSPACE/build/release/$TARGET"
TIMESTAMP=`date +%Y%m%d`
BUILD_ID=${BUILD_ID:-$TIMESTAMP}
CCACHE_DIR="$WORKSPACE/build/cache/$TARGET/ccache"

die() {
  echo "Error:" $@
  echo "Make sure your sources are compilable and run this script only in qt5-build-environment-mingw container."
  exit -1
}

cd "$WORKSPACE"
rm -rf "$BUILD_DIR"
rm -rf "$DIST_DIR"
rm -rf "$RELEASE_DIR"
mkdir -p "$CCACHE_DIR"
mkdir -p "$BUILD_DIR"
mkdir -p "$RELEASE_DIR"

cd $BUILD_DIR
$TARGET-cmake -DCMAKE_INSTALL_PREFIX=$DIST_DIR -DCMAKE_BUILD_TYPE=MinSizeRel -DVERSION_FROM_GIT=true $WORKSPACE || die "Unable to configure the program"
make -j`nproc` || die "Unable to build the program"
make install

$WORKSPACE/thirdparty/mxedeployqt/mxedeployqt --qtplugins="iconengines;imageformats;platforminputcontexts;platforms;sqldrivers;styles" \
                                              --skiplibs="qsqlmysql.dll;qsqlodbc.dll;qsqlpsql.dll;qsqltds.dll" \
                                              --additionallibs="libwinpthread-1.dll;icudt56.dll;icuin56.dll;icuuc56.dll" \
                                              --mxepath=/usr/ --mxetarget $TARGET --qmlrootpath=$WORKSPACE/qml $DIST_DIR || die "Unable to bundle the needed libraries"

cd "$RELEASE_DIR"
cp "$BUILD_DIR/installer.nsis" .
makensis -V4 "installer.nsis" || die "Unable to create installer"
rm "installer.nsis"
